name: ci

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test ${{ matrix.os }} rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v4

      - name: Install Homebrew llvm on macOS
        if: matrix.os == 'macos-latest'
        run: brew install llvm

      - run: rustup default ${{ matrix.rust }}
      - run: rustup update ${{ matrix.rust }}
      - run: rustup target add wasm32-unknown-unknown
      - run: curl -L -o code.tar.gz https://github.com/rust-lang/llvm-project/archive/rustc/17.0-2023-12-14.tar.gz
      - run: tar xzf code.tar.gz --strip-components 3 llvm-project-rustc-17.0-2023-12-14/compiler-rt/lib/builtins
      - run: rm code.tar.gz
      - run: find builtins -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +
      - run: cargo build --target wasm32-unknown-unknown
      - run: cargo publish --allow-dirty --dry-run

  publish:
    needs: [test]
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'compiler-rt-builtins@') && github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v4

      - run: rustup default stable
      - run: rustup update stable
      - run: curl -L -o code.tar.gz https://github.com/rust-lang/llvm-project/archive/rustc/17.0-2023-12-14.tar.gz
      - run: tar xzf code.tar.gz --strip-components 3 llvm-project-rustc-17.0-2023-12-14/compiler-rt/lib/builtins
      - run: rm code.tar.gz
      - run: find builtins -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +
      - run: cargo publish --allow-dirty --token ${{ secrets.CARGO_TOKEN }}
